# File: azure-template-build.yml
# Date: 15-Aug-2025 ep create to build wheels
#
# Update:
#
##
parameters:
  tox: ""
  python: ""
  os: "linux"
  fixtures: ""

jobs:
- job: ${{ format('build_packages_{0}_{1}', parameters.tox, parameters.os) }}

  pool:
    ${{ if eq(parameters.os, 'macos') }}:
      vmImage: 'macOS-latest'
    ${{ if eq(parameters.os, 'linux') }}:
      vmImage: 'ubuntu-latest'
  dependsOn: ${{ format('build_test_{0}_{1}', parameters.tox, parameters.os) }}
  #
  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: ${{ parameters.python }}
        addToPath: true
      displayName: setup python

    # Checkout repository
    - checkout: self
      submodules: true

    - script: pip install --upgrade pip cibuildwheel==3.2.1 build
      displayName: Install build tools

    # Build sdist on linux
    - ${{ if startsWith(parameters.os, 'linux') }}:
      - script: python -m build --sdist --outdir "$(System.DefaultWorkingDirectory)/dist"
        displayName: "Build source dist"

    # We use the manylinux2014 to ensure compatibility with centos-7 for now.  The 2_17 glibc
    - script: |
        rm -rf "$(System.DefaultWorkingDirectory)/build"
        export CIBW_MANYLINUX_X86_64_IMAGE="manylinux2014" ; cibuildwheel --output-dir "$(System.DefaultWorkingDirectory)/dist" .
      displayName: "Build binary wheels"

    # Check the install artifacts
    - script: ls -lR "$(System.DefaultWorkingDirectory)/dist"
      displayName: "Listing of installed software"
   #
    - publish: $(System.DefaultWorkingDirectory)/dist
      artifact: ${{ format('sw_{0}_{1}_pkg', parameters.tox, parameters.os) }}
